version: "3"
services:
    exred_db:
        image: zsolt001/exred_db:latest
        volumes:
            - ~/exred_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - exrednet
        env_file: env_file
    exred_scheduler:
        image: exred_scheduler:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        ports:
            - "10001:10001"
        networks:
            - exrednet
        env_file: ./env_file
        command: ["/usr/local/bin/wait-for-postgres.sh", "-r", "30", "--", "/app/bin/exred_scheduler", "foreground"]
        #command: ["tail", "-f", "/dev/null"]
    exred_ui:
        image: exred_ui:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        ports:
            - "4000:4000"
        networks:
            - exrednet
        env_file: ./env_file
        command: ["/usr/local/bin/wait-for-postgres.sh", "-r", "30", "--", "/app/bin/exred_ui", "foreground"]
        #command: ["tail", "-f", "/dev/null"]
        
    redis:
        image: redis:5-alpine
        hostname: redis
        networks:
            - exrednet
        ports:
            - "6379:6379"
        command: ["redis-server"]
networks:
    exrednet:
