version: "2"
services:
    exred_db:
        image: zsolt001/exred_db_rpi:latest
        volumes:
            - ~/exred_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - exrednet
        env_file: env_file
    exred:
        image: zsolt001/exred_rpi:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        ports:
            - "4000:4000"
        networks:
            - exrednet
        env_file: env_file
        privileged: true
        command: ["/usr/local/bin/wait-for-postgres.sh", "-r", "30", "--", "/app/bin/exred", "foreground"]
        #command: ["/usr/local/bin/wait-for-it.sh", "exred_db:5432", "-t", "30", "-s", "--", "/app/bin/exred", "foreground"]
networks:
    exrednet:
