version: "2"
services:
    exred_db:
        image: zsolt001/exred_db_rpi:latest
        volumes:
            - ~/exred_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - exrednet
        env_file: env_file
    exred_ui:
        image: zsolt001/exred_ui_rpi:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        ports:
            - "4000:4000"
        networks:
            - exrednet
        env_file: ./env_file
        command: ["/usr/local/bin/wait-for-postgres.sh", "-r", "30", "--", "/app/bin/exred_ui", "foreground"]
    exred_scheduler:
        image: zsolt001/exred_scheduler_rpi:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        networks:
            - exrednet
        env_file: ./env_file
        command: ["/usr/local/bin/wait-for-postgres.sh", "-r", "30", "--", "/app/bin/exred_scheduler", "foreground"]
    redis:
        image: arm32v7/redis:5
        hostname: redis
        networks:
            - exrednet
        ports:
            - "6379:6379"
        command: ["redis-server"]
networks:
    exrednet:
